# application.yml
# tomcat
server:
  port: 8080
  servlet:
    context-path: /pet
    session:
      timeout: 30m

# spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: pet
#    password: pet
  servlet:
   multipart:
     max-file-size: 10MB
     max-request-size: 50MB
     location: 
  security:
    oauth2:
      client: 
        registration: 
          kakao:
            client-id: 9e787ad9e987e36fe934ff7373c1a656
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
          naver:
            client-id: u4bMDPmPAuX3BG3drYLV
            client-secret: IjXlW5kGK9
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me  
            user-name-attribute: response

# logback
logging:
  level:
    root: info
    '[com.shop.app]': debug
    
# mybatis
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.shop.app, org.springframework.security.core.authority
  type-handlers-package: com.shop.app.common.typehandler
  mapper-locations: classpath:mapper/**/*-mapper.xml
  type-handlers:
    - handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
      javaType: com.shop.app.terms.entity.Accept

# iamport
external:
  api:
    name: iamport
    key: 8436154361367252
    secret: KFOGi0l3xtHvta03STsSgbxGPTUEdoQ8nvwXsPiS86MffGCYzXUoYvX7SL5V7P4NDyu5rGHirJXjbXA3

# oauth
oauth:
  kakao:
    authorize-uri: https://kauth.kakao.com/oauth/authorize/
    redirect-uri: http://localhost:8080/pet/oauth/kakao/callback.do
    rest-api-key: 9e787ad9e987e36fe934ff7373c1a656
    token-uri: https://kauth.kakao.com/oauth/token
    scope: profile_nickname, account_email, profile_image
    resource-uri-host: https://kapi.kakao.com
  naver:
    client-id: u4bMDPmPAuX3BG3drYLV
    client-secret: IjXlW5kGK9    
    authorize-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: http://localhost:8080/pet/login/oauth2/code/naver
    resource-uri-host: https://openapi.naver.com/v1/nid/me
    token-uri: https://nid.naver.com/oauth2.0/token
    profile-uri: https://openapi.naver.com/v1/nid/me